#!/usr/bin/env python
import os
import sys
import django
from django.apps import apps
from django.conf import settings
from django.db.models.fields.reverse_related import (
    ManyToManyRel, ManyToOneRel, OneToOneRel
)
from django.db.models.fields.related import ForeignKey, ManyToManyField, OneToOneField
from django.db.models.fields import NOT_PROVIDED

# --- Configuration ---
# This script assumes it's run from the root of a project generated by initialize_new_project.py
# where the Django project resides in a 'backend/' subdirectory.
DJANGO_PROJECT_DIR = "backend"  # Relative to where this script is run from (template root)
DJANGO_SETTINGS_MODULE_PATTERN = "{project_name_slug}.settings" # {project_name_slug} will be the Django project folder

def setup_django_env(project_root_path):
    """
    Sets up the Django environment to allow model introspection.
    Assumes the Django project is in a subdirectory (e.g., 'backend').
    """
    backend_dir = os.path.join(project_root_path, DJANGO_PROJECT_DIR)
    if not os.path.isdir(backend_dir):
        print(f"Error: Django project directory '{backend_dir}' not found.")
        print("Please run this script from the root of a generated project, or ensure 'backend/' exists.")
        sys.exit(1)

    # Attempt to find the Django project name (settings directory)
    # This is a simple heuristic; might need adjustment for complex setups.
    potential_settings_dirs = [d for d in os.listdir(backend_dir) if os.path.isdir(os.path.join(backend_dir, d))]
    
    project_name_slug = None
    for pname in potential_settings_dirs:
        if os.path.exists(os.path.join(backend_dir, pname, 'settings.py')):
            project_name_slug = pname
            break
    
    if not project_name_slug:
        print(f"Error: Could not automatically determine Django project name (settings directory) within '{backend_dir}'.")
        sys.exit(1)

    sys.path.append(backend_dir) # Add backend dir to path to find manage.py and project
    sys.path.append(project_root_path) # Add project root to path

    settings_module = DJANGO_SETTINGS_MODULE_PATTERN.format(project_name_slug=project_name_slug)
    
    try:
        os.environ.setdefault('DJANGO_SETTINGS_MODULE', settings_module)
        django.setup()
        print(f"Django environment initialized with settings: {settings_module}")
    except Exception as e:
        print(f"Error setting up Django environment with settings '{settings_module}': {e}")
        print("Ensure your Django project is correctly configured and all dependencies are installed.")
        sys.exit(1)


def map_django_field_to_dbml_type(field):
    """Maps Django field types to basic DBML types."""
    if field.is_relation:
        if isinstance(field, (ForeignKey, OneToOneField)):
            # For FKs/O2Os, the type is often implied by the reference or can be the PK type of the related model
            # For simplicity, we'll just use a generic type or let DBML infer.
            # DBML usually just needs the column name for FKs. The type is the PK of the target.
            # We will handle relationships separately.
            return field.related_model._meta.pk.get_internal_type() # Get PK type of related model
        elif isinstance(field, ManyToManyField):
            return None # M2M doesn't directly translate to a single column type in DBML table def
    
    # Basic type mapping
    if isinstance(field, (models.AutoField, models.BigAutoField)): return "bigint" # Or int
    if isinstance(field, models.IntegerField): return "int"
    if isinstance(field, models.SmallIntegerField): return "smallint"
    if isinstance(field, models.BooleanField): return "boolean"
    if isinstance(field, models.CharField): return f"varchar({field.max_length})" if field.max_length else "varchar"
    if isinstance(field, models.TextField): return "text"
    if isinstance(field, models.DateField): return "date"
    if isinstance(field, models.DateTimeField): return "timestamp" # Or datetime
    if isinstance(field, models.TimeField): return "time"
    if isinstance(field, models.DecimalField): return f"decimal({field.max_digits}, {field.decimal_places})"
    if isinstance(field, models.FloatField): return "float" # Or double
    if isinstance(field, models.UUIDField): return "uuid"
    if isinstance(field, models.EmailField): return "varchar" # Often represented as varchar
    if isinstance(field, models.URLField): return "varchar"
    if isinstance(field, models.JSONField): return "json" # Or jsonb for PostgreSQL

    return "text" # Default fallback

def get_dbml_constraints(field):
    """Generates DBML constraints string for a field."""
    constraints = []
    if field.primary_key:
        constraints.append("pk")
        if isinstance(field, (models.AutoField, models.BigAutoField)):
            constraints.append("increment")
        elif isinstance(field, models.UUIDField) and field.default == models.UUIDField._defaulter: # Heuristic for auto-generated UUID
             # DBML often uses `default: uuid_generate_v4()` or similar for auto UUIDs
             # This is a simplification.
            pass # `uuid [pk]` is often enough
    
    if field.unique and not field.primary_key:
        constraints.append("unique")
    if not field.null and not field.primary_key: # PKs are implicitly not null
        constraints.append("not null")
    
    if field.default != NOT_PROVIDED and field.default is not None:
        default_val = field.default
        if isinstance(default_val, str):
            constraints.append(f"default: '{default_val}'")
        elif isinstance(default_val, bool):
            constraints.append(f"default: {str(default_val).lower()}")
        elif callable(default_val):
             # For callables like timezone.now, DBML uses `now()`
            if default_val.__name__ == 'now' and 'timezone' in str(default_val): # Heuristic
                constraints.append("default: `now()`")
            else:
                constraints.append(f"default: `'{default_val.__name__}()'`") # Generic callable
        else:
            constraints.append(f"default: {default_val}")
            
    if hasattr(field, 'choices') and field.choices:
        # DBML doesn't have direct enum constraints in column def like this,
        # Enums are defined separately. This is more of a note.
        # We will try to generate Enums separately.
        pass

    return f"[{', '.join(constraints)}]" if constraints else ""

def generate_dbml_for_model(model):
    """Generates DBML string for a single Django model."""
    dbml_lines = []
    table_name = model._meta.object_name # PascalCase by convention
    dbml_lines.append(f"Table {table_name} {{")

    for field in model._meta.get_fields():
        if isinstance(field, (ManyToManyRel, ManyToOneRel, OneToOneRel)):
            # These are reverse relations, handled by the "forward" side of the relation
            continue

        col_name = field.column
        if not col_name: # e.g. for some M2M fields or generic relations
            continue

        col_type_mapped = map_django_field_to_dbml_type(field)
        if col_type_mapped is None: # M2M fields
            continue

        constraints = get_dbml_constraints(field)
        
        # Handle choices by trying to infer an Enum name
        enum_name = None
        if hasattr(field, 'choices') and field.choices:
            enum_name = f"{table_name}{field.name.capitalize()}Enum" # Suggested Enum name
            col_type_mapped = enum_name # Use Enum name as type

        dbml_lines.append(f"  {col_name} {col_type_mapped} {constraints}")

        # Add relationship for ForeignKey and OneToOneField
        if isinstance(field, (ForeignKey, OneToOneField)):
            related_table = field.related_model._meta.object_name
            related_pk = field.related_model._meta.pk.column
            # DBML ref syntax: ref: > other_table.other_pk_column
            # We need to add this to the constraints string if not already there.
            # The get_dbml_constraints doesn't add 'ref' directly.
            # Let's add it here.
            ref_constraint = f"ref: > {related_table}.{related_pk}"
            if constraints:
                dbml_lines[-1] = dbml_lines[-1].replace("]", f", {ref_constraint}]")
            else:
                dbml_lines[-1] += f" [{ref_constraint}]"
                
    dbml_lines.append("}\n")
    return "\n".join(dbml_lines)

def generate_enums_for_model_fields(model):
    """Generates DBML Enum definitions for fields with choices."""
    enum_defs = []
    table_name = model._meta.object_name
    for field in model._meta.get_fields():
        if hasattr(field, 'choices') and field.choices:
            enum_name = f"{table_name}{field.name.capitalize()}Enum"
            enum_def = [f"Enum {enum_name} {{"]
            for value, display_name in field.choices:
                # DBML enum values are typically simple strings or identifiers
                # We'll use the value, ensuring it's a valid identifier (e.g., no spaces)
                enum_value_cleaned = str(value).replace(" ", "_").upper()
                enum_def.append(f"  {enum_value_cleaned} // \"{display_name}\"")
            enum_def.append("}\n")
            enum_defs.append("\n".join(enum_def))
    return "\n".join(enum_defs)


def main():
    project_root = os.getcwd() # Assume script is run from project root
    setup_django_env(project_root)

    all_dbml_output = []
    all_enum_output = []
    
    # Standard header
    all_dbml_output.append(f"// DBML generated from Django models for project")
    all_dbml_output.append(f"// Project: MyProjectName (Replace with actual project name)")
    all_dbml_output.append(f"Project MyProjectName {{") # Basic project block
    all_dbml_output.append(f"  database_type: 'PostgreSQL'") # Default to PostgreSQL
    all_dbml_output.append(f"  Note: 'Generated automatically. Review and enhance.'")
    all_dbml_output.append(f"}}\n")


    print("\nGenerating DBML for installed models...")
    
    processed_models = set() # To avoid processing proxy models multiple times if base is also processed
    
    for app_config in apps.get_app_configs():
        # Optional: filter for specific apps if needed
        # if app_config.name not in ['users_app', 'main_app', 'permissions_app']:
        #     continue
        print(f"\n// --- App: {app_config.name} ---")
        all_dbml_output.append(f"\n// --- App: {app_config.name} ---")
        
        for model in app_config.get_models():
            if model in processed_models:
                continue
            if model._meta.proxy: # Skip proxy models if their concrete model is processed
                # Check if concrete model is from a different app to avoid missing it
                if model._meta.concrete_model._meta.app_config in apps.get_app_configs():
                     processed_models.add(model) # Mark as processed to avoid re-processing
                     continue

            print(f"Processing model: {model._meta.object_name} ({model._meta.app_label})")
            
            enum_defs = generate_enums_for_model_fields(model)
            if enum_defs:
                all_enum_output.append(enum_defs)

            model_dbml = generate_dbml_for_model(model)
            all_dbml_output.append(model_dbml)
            processed_models.add(model)

    # Output Enums first
    if all_enum_output:
        print("\n\n// --- Enums ---")
        print("\n".join(all_enum_output))
    
    # Output Tables
    print("\n\n// --- Tables ---")
    print("\n".join(all_dbml_output))

    # TODO: Add M2M relationship tables (Ref definitions)
    # This requires iterating through M2M fields again after all tables are defined.
    # Example: Ref: posts.id < posts_tags.post_id
    # Example: Ref: tags.id < posts_tags.tag_id
    # Table posts_tags { post_id integer; tag_id integer; }

    output_filename = "generated_schema.dbml"
    with open(output_filename, "w", encoding="utf-8") as f:
        if all_enum_output:
            f.write("// --- Enums ---\n")
            f.write("\n".join(all_enum_output))
            f.write("\n\n")
        f.write("// --- Tables ---\n")
        f.write("\n".join(all_dbml_output))
    print(f"\nDBML output saved to {output_filename}")


if __name__ == "__main__":
    # This script needs to be run in the context of a Django project.
    # Typically, you'd run it from the root of your generated project:
    # python ../TEMPLATE_PROJECT_OUTPUT/scripts/generation/generate_dbml_from_django_models.py
    # Or, if the script is copied into the new project's scripts/generation/ folder:
    # python scripts/generation/generate_dbml_from_django_models.py
    main()