#!/usr/bin/env python
import os
import re
import argparse

# --- Configuration ---
# Assumes script is run from the root of a project generated by initialize_new_project.py
# where the frontend project resides in a 'frontend/' subdirectory.
FRONTEND_SRC_DIR_DEFAULT = "frontend/src"

# Regex patterns (can be refined)
IMPORT_USE_ERROR_HANDLER_PATTERN = r"import\s+.*useErrorHandler.*from\s+['\"].*useErrorHandler['\"]"
# Looks for: const { error, handleError, ... } = useErrorHandler(...);
USE_ERROR_HANDLER_HOOK_PATTERN = r"useErrorHandler\s*\("
# Looks for: <ErrorDisplay ... />
ERROR_DISPLAY_COMPONENT_PATTERN = r"<\s*ErrorDisplay\s+.*/>"
# Looks for: handleError(...)
HANDLE_ERROR_CALL_PATTERN = r"handleError\s*\("

def validate_react_error_handling(frontend_src_dir):
    """
    Scans React components for basic adherence to error handling patterns.
    Returns a list of warnings.
    """
    warnings = []

    if not os.path.isdir(frontend_src_dir):
        warnings.append(f"Frontend source directory not found: {frontend_src_dir}")
        return warnings

    for root, _, files in os.walk(frontend_src_dir):
        for filename in files:
            if filename.endswith((".js", ".jsx")):
                filepath = os.path.join(root, filename)
                try:
                    with open(filepath, 'r', encoding='utf-8') as f:
                        content = f.read()

                    has_import_use_error_handler = bool(re.search(IMPORT_USE_ERROR_HANDLER_PATTERN, content))
                    uses_hook = bool(re.search(USE_ERROR_HANDLER_HOOK_PATTERN, content))
                    uses_error_display = bool(re.search(ERROR_DISPLAY_COMPONENT_PATTERN, content))
                    calls_handle_error = bool(re.search(HANDLE_ERROR_CALL_PATTERN, content))

                    if has_import_use_error_handler or uses_hook:
                        if not calls_handle_error:
                            warnings.append(
                                f"File '{filepath}': Imports or uses 'useErrorHandler' but no clear call to 'handleError(...)' found. "
                                f"Ensure errors are passed to the handler."
                            )
                        if not uses_error_display:
                            warnings.append(
                                f"File '{filepath}': Imports or uses 'useErrorHandler' but no '<ErrorDisplay ... />' component usage found. "
                                f"Ensure errors are displayed to the user."
                            )
                    elif calls_handle_error and not (has_import_use_error_handler or uses_hook) :
                         warnings.append(
                                f"File '{filepath}': Calls 'handleError(...)' but 'useErrorHandler' hook import or usage is not apparent."
                            )
                    elif uses_error_display and not (has_import_use_error_handler or uses_hook) :
                        warnings.append(
                                f"File '{filepath}': Uses '<ErrorDisplay ... />' but 'useErrorHandler' hook import or usage is not apparent."
                            )


                except Exception as e:
                    warnings.append(f"Could not process file '{filepath}': {e}")
    return warnings

def main():
    parser = argparse.ArgumentParser(description="Check React components for basic error handling patterns.")
    parser.add_argument(
        "src_dir",
        nargs="?",
        default=FRONTEND_SRC_DIR_DEFAULT,
        help=f"Path to the frontend src directory. Defaults to '{FRONTEND_SRC_DIR_DEFAULT}' relative to project root."
    )
    args = parser.parse_args()

    src_dir_to_check = args.src_dir
    if not os.path.isabs(src_dir_to_check):
        src_dir_to_check = os.path.join(os.getcwd(), src_dir_to_check)

    print(f"Checking React error handling patterns in: {src_dir_to_check}\n")
    warnings = validate_react_error_handling(src_dir_to_check)

    if warnings:
        print("--- Potential Error Handling Issues Found ---")
        for warning in warnings:
            print(f"- {warning}")
        print(f"\nFound {len(warnings)} potential issue(s). Manual review recommended.")
        # exit(1) # Optionally exit with error code if warnings are critical
    else:
        print("No obvious error handling pattern deviations found by this basic check.")

if __name__ == "__main__":
    # This script should be run from the root of a generated project:
    # python ../TEMPLATE_PROJECT_OUTPUT/scripts/validation/check_error_handling_patterns_react.py
    # Or, if copied into the new project's scripts/validation/ folder:
    # python scripts/validation/check_error_handling_patterns_react.py frontend/src
    main()